"""Seed the backend with the Oystermouth test site and SYNTHETIC field-test data.

Every session row is generated by replaying the Prototype A fusion mock
scenarios (fusion/mocks.py) with per-run variation — not hand-typed numbers —
and every row carries source="synthetic". The web UI labels synthetic data
wherever it appears; nothing here may masquerade as field results (spec:
"do not fabricate field-test results").

The seed deliberately includes a run of recent low-confidence dusk sessions so
self-learning v0 has a real pattern to react to.

Run:  cd shared-infrastructure/backend && python seed_synthetic.py
"""

from __future__ import annotations

import random
import shutil
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parents[2]
sys.path.insert(0, str(REPO_ROOT / "prototype-a-xreal-now"))

from fusion import mocks  # noqa: E402
from fusion.session import run_session  # noqa: E402
from fusion.state_machine import FusionThresholds  # noqa: E402

from app import models  # noqa: E402
from app.database import Base, SessionLocal, engine  # noqa: E402

SITE_ID = "oystermouth-chapel"
rng = random.Random(2026)


def jittered(scenario_factory, days_ago: float, lighting: str | None = None):
    scenario = scenario_factory()
    if lighting:
        scenario = type(scenario)(scenario.name, scenario.description, scenario.ticks, lighting)
    started = datetime.now(timezone.utc) - timedelta(days=days_ago, minutes=rng.randint(0, 600))
    record = run_session(scenario, site_id=SITE_ID, source="synthetic", started_at=started)
    # Per-run measurement noise so aggregates aren't degenerate.
    record["gps_accuracy_m"] = round(min(999.0, record["gps_accuracy_m"] * rng.uniform(0.8, 1.3)), 3)
    record["time_to_lock_s"] = round(record["time_to_lock_s"] * rng.uniform(0.7, 2.5), 3)
    record["drift_m"] = round(rng.uniform(0.01, 0.35), 3)
    if record["visual_confidence"] > 0:
        record["visual_confidence"] = round(min(1.0, max(0.0, record["visual_confidence"] + rng.uniform(-0.02, 0.02))), 3)
    return record


def build_seed_records() -> list[dict]:
    records = []
    # Two weeks of mixed sessions: mostly clean locks, some urban-canyon walks.
    for day in range(14, 4, -1):
        records.append(jittered(mocks.clean_fused_lock, day))
        if day % 3 == 0:
            records.append(jittered(mocks.urban_canyon, day))
        if day % 5 == 0:
            records.append(jittered(mocks.tracking_loss_relocalization, day))
    # Recent pattern for the self-learning loop: repeated dusk sessions where
    # confidence lands just under the 0.70 cutoff but the anchor fallback still
    # delivered (outcome=degraded, low drift) -> loop should consider loosening.
    for day in (4, 3, 3, 2, 2, 1, 1, 0):
        records.append(jittered(mocks.dusk_never_locks, day))
    records.append(jittered(mocks.no_target_cell, 6))
    records.append(jittered(mocks.gps_dead_no_anchor, 9))
    return records


def main() -> None:
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        if db.get(models.Site, SITE_ID):
            print(f"site '{SITE_ID}' already seeded — nothing to do")
            return

        db.add(models.Site(
            id=SITE_ID,
            name="Oystermouth Castle Chapel",
            lat=51.5720, lon=-4.0130,
            recognition_target_status="ready",
        ))
        db.add(models.ThresholdVersion(
            site_id=SITE_ID, version=1,
            gps_accuracy_good_m=10.0, visual_confidence_min=0.70,
            changed_by="operator", reason="initial defaults",
        ))

        records = build_seed_records()
        for r in records:
            db.add(models.FieldTestSession(
                **{k: v for k, v in r.items() if k not in ("schema_version", "time_of_day_local")}
            ))
        db.commit()

        # Give the 3D preview a real asset: LOD1 from the pipeline output, if present.
        lod1 = REPO_ROOT / "prototype-a-xreal-now" / "output" / "chapel_lod1.glb"
        if lod1.exists():
            dest = Path("storage") / SITE_ID
            dest.mkdir(parents=True, exist_ok=True)
            shutil.copy(lod1, dest / "scan.glb")
            site = db.get(models.Site, SITE_ID)
            site.model_asset_path = str(dest / "scan.glb")
            db.commit()
            print(f"model asset: {dest / 'scan.glb'} (pipeline LOD1, placeholder mesh)")
        else:
            print("NOTE: run prototype-a pipeline first to give the 3D preview an asset")

        outcomes = {}
        for r in records:
            outcomes[r["outcome"]] = outcomes.get(r["outcome"], 0) + 1
        print(f"seeded {len(records)} SYNTHETIC sessions for '{SITE_ID}': {outcomes}")
    finally:
        db.close()


if __name__ == "__main__":
    main()
